# MyBiOut! 配置文件

[export]
path = C:\MyBiOut!

[api]
key = 
model = 

[localout]
folder = localout!
scan_android = false
bilibili_pc_cache_path = C:\Users\linzh\Videos\bilibili
bilibili_pc_cache_optional_when_installed = true
scan_interval = 1s
name_parts = bv,title,up,group,part,publish_time,export_time
incomplete_title_action = partial_or_folder
ffmpeg_concurrent = 3

[bbdown]
folder = bbdown!
cookie = 
encoding_priority = 
quality_priority = 
download_danmaku = false
skip_subtitle = false
skip_cover = false
file_pattern = <videoTitle>
multi_file_pattern = <videoTitle>/[P<pageNumberWithZero>]<pageTitle>
use_aria2c = false

[mdout]
folder = mdout!
sessdata = 
include_cover = true
include_tags = true
include_stats = true
favorite_detail = basic
request_delay = 0.5
