# MyBiOut! 配置文件

[export]
path = C:\MyBiOut!
sessdata = 

[api]
key = 
model = gpt-5.3-codex
base_url = https://api.poe.com/v1
timeout = infinite

[localout]
folder = localout!
bilibili_pc_cache_path = C:\Users\linzh\Videos\bilibili
bilibili_pc_cache_optional_when_installed = true
name_parts = title
incomplete_title_action = partial_or_folder
ffmpeg_concurrent = 3

[bbdown]
folder = bbdown!
cookie = 
encoding_priority = 
quality_priority = 
download_danmaku = false
skip_subtitle = false
skip_cover = false
file_pattern = <videoTitle>
multi_file_pattern = <videoTitle>/[P<pageNumberWithZero>]<pageTitle>
use_aria2c = false

[mdout]
folder = mdout!
sessdata = 
include_cover = true
include_tags = true
include_stats = true
favorite_detail = basic
request_delay = 0.5

