# MyBiOut! 配置文件

[export]
path = C:\MyBiOut!

[api]
key = 
model = 

[localout]
folder = localout!
scan_android = true
scan_bilibili_pc = true
scan_interval = 1s
crawl_title = true
crawl_fail_action = export_without_title
crawl_timeout = 2s
ffmpeg_concurrent = 3

[bbdown]
folder = bbdown!

[mdout]
folder = mdout!

